name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest
    env:
      PERL_CPANM_OPT: "--quiet --notest"


    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: brew install perl
      - name: Set up cpanm
        run: brew install cpanm
      - name: perl -V
        run: perl -V
      - name: Install Dist::Zilla
        run: cpanm Dist::Zilla
      - name: Install author dependencies
        run: dzil authordeps | cpanm
      - name: Install dependencies
        run: dzil listdeps --develop | cpanm
      - name: Run perlcritic
        run: perlcritic lib t xt
      - name: Run tests
        run: dzil test --all
